# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 1575

# MD033/no-inline-html - Inline HTML
MD033:
  # Allowed elements
  allowed_elements:
    - a
    - hr
    - iframe
    - img

# MD034/no-bare-urls - Bare URL used
MD034: false
