title: rubysecurity.org
email: root@antoniobaltazar.com
description: >- # this means to ignore newlines until "baseurl:"
  Anecdotes from a Linux Systems Administrator. /root
theme: jekyll-theme-hacker
