title: rubysecurity.org
email: root@antoniobaltazar.com
description: >- # this means to ignore newlines until "theme:"
  Anecdotes from a Linux Systems Administrator. /root
theme: jekyll-theme-hacker
twitter_username: alpha01
github_username:  alpha01
permalink: /:categories/:title
google_analytics:
url: ""
baseurl: ""
author: Alpha01
header_pages:
  - about.md
  - category/books.md
plugins:
  - jekyll-feed
  - jekyll-toc
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
repository: alpha01/rubysecurity.org
markdown: kramdown
paginate: 5
paginate_path: /posts/page:num/
collections:
  books:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
