title: rubysecurity.org
email: root@antoniobaltazar.com
description: >- # this means to ignore newlines until "baseurl:"
  Anecdotes from a Linux Systems Administrator. /root
theme: jekyll-theme-hacker
twitter_username: alpha01
github_username:  alpha01
permalink: /:categories/:title
url: alpha01.github.io
baseurl: /rubysecurity.org/
author: Alpha01
header_pages:
  - about.md
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
